### ISSUE TITLE
Be able to search through Resources in other channels

### ISSUE THREAD

**Issue by jayoshih** [learningequality/sushibar#157]
As a user, I would like to be able to do a keyword search through the contents in my channels as an alternative to manually traversing the tree view.

## Scenario
Given that I have some content with the keyword "foo" in its title,
When I initiate a search with keyword "foo"
Then I am presented with the contents (topics and documents) referenced above

## Other Details
This story is a prerequisite for enabling a workflow for importing these contents after they are searched for.

## Tasks
* [ ] Expose an API endpoint for searching through topics and other resources.
* [ ] Implement UI for user to provide search term
* [ ] Implement UI for user to view search results

## Implementation Details
* Add new API endpoint `api/search/document/` that takes a query paramter `q` with the search terms. Returns a list of `ContentNodes` but serialized to show only the minimal subset of data.
* Search endpoint filters out channels that are not accessible to the authenticated user.
* Search endpoint can include a `exclude_channel` parameter to filter out one channel from results. Can extend to multiple channel ids if requirement arises.
